require File.join(File.dirname(__FILE__), 'organizer')
require File.join(File.dirname(__FILE__), 'parse_detail')
require File.join(File.dirname(__FILE__), 'parse_newegg')
require File.join(File.dirname(__FILE__), 'parse_walmart')
require File.join(File.dirname(__FILE__), 'parse_rakuten')